name = "cdr-ta-ufl-dashboard"
main = "src/index.js"
compatibility_date = "2026-09-25"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "cdr-ta-ufl"
database_id = "REPLACE_WITH_YOUR_EXISTING_D1_DATABASE_ID"
migrations_dir = "migrations"
